- name: Install dependencies of python
  apt:
    name:
      - build-essential
      - cmake
      - git
      - python3-colcon-common-extensions
      - python3-flake8
      - python3-pytest-cov
      - python3-rosdep
      - python3-setuptools
      - python3-vcstool
      - wget
  become: true

- name: install some python modules for caret
  pip:
    name:
      - flake8-blind-except
      - flake8-builtins
      - flake8-class-newline
      - flake8-comprehensions
      - flake8-deprecated
      - flake8-docstrings
      - flake8-import-order
      - flake8-quotes
      - pytest-repeat
      - pytest-rerunfailures
      - pytest
      - setuptools
    executable: pip3
  become: true

- name: Install ros-tracing
  apt:
    name:
      - ros-galactic-ros2trace
      - ros-galactic-ros2trace-analysis
      - ros-galactic-tracetools
      - ros-galactic-tracetools-analysis
      - ros-galactic-tracetools-launch
      - ros-galactic-tracetools-read
      - ros-galactic-tracetools-test
      - ros-galactic-tracetools-trace
  become: true
